version: '3'
services:
  nodejs-server:
    build:
      context: ./api
      dockerfile: Dockerfile-dev
    ports:
      - "3080:3080"
    container_name: node-api-twerlo
    volumes:
       - ./api:/usr/src/app/api
       - /usr/src/app/api/node_modules
  angular-ui-twerlo:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    ports:
      - "4201:4201"
    container_name: angular-ui-twerlo
    volumes:
       - ./frontend:/usr/src/app/frontend
       - /usr/src/app/frontend/node_modules
